modLoader="javafml"
loaderVersion="[53,)"
issueTrackerURL="https://github.com/arollyson/FasterLadderClimbing/issues"
license="CC-BY-NC-SA 3.0"
showAsResourcePack=false
clientSideOnly=true

[[mods]]
modId="fasterladderclimbing"
displayName="Faster Ladder Climbing"
version="0.2.9"
authors="JaSpr, forkbomb_"
description='''
Climb Ladders Faster
'''
#forge
[[dependencies.fasterladderclimbing]]
    modId="forge"
    mandatory=true
    versionRange="[53.0.25,)"
    ordering="NONE"
    side="CLIENT"

#minecraft
[[dependencies.fasterladderclimbing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.3]"
    ordering="NONE"
    side="CLIENT"